# -*- coding: utf-8 -*-
"""StructShot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16PJgWyBcU1raseIISePqgYeZ5VhSrk04
"""



!git clone https://github.com/chriswu99aaa/structshot.git

import os
os.chdir("/content/structshot")



!pip install -e .
!cd structshot

os.chdir("/content/structshot/structshot")

# Pretrain a conventional BERT-NER model on CoNLL 2003
!bash run_pl.sh

!ls

